### ISSUE TITLE
Stuttering audio on auto mode

### ISSUE THREAD

**Issue by ppzz123** [nikitakatchik/smarttv-twitch#101]
My TV: Samsung UE22F5400 connected to my network with a cable (so no WiFi).

I'm a long time user of your amazing app. Since a while (couple of months or more probably) the audio of the channels I'm watching is stuttering when the stream quality is in auto mode. The video seems fine. Whenever I switch to 720p the audio isn't stuttering anymore. 

I can't really rule out that my TV or my router is the cause for this but for example: my Netflix or Youtube streams on the same TV aren't stuttering and I used to watch Twitch with your app without stutters. Is there anything I or you can do to fix this?

Thanks in advance

**Comment by nikitakatchik** [comment]
Hi. It's most likely TV not being able to handle video format selected automatically. App has very little control of anything so you should just use 720p I think. Also, the problem with auto mode is that TV tries to download 2 streams at once so it can switch seamlessly. So there is a small chance that download speed is not enough for that.
