### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by Snoeprol** [nikitakatchik/smarttv-twitch#102]
Everything works for me except the last step to sync. My tv just says connecting....

**Comment by Snoeprol** [comment]
connected to internet so that shouldn't be the problem

**Comment by kugelblit** [comment]
Same problem for me. Other times it just fails to connect to the server at all.

**Comment by rodrigo-weigert** [comment]
Same here.

**Comment by Snoeprol** [comment]
185.49.13.73 This IP works

**Comment by rodrigo-weigert** [comment]
I managed to install it setting up my own HTTP server. But I wasn't able to watch a single stream - I either get "Format not supported" or a black screen. Also the navigation is all weird, the screen seems to scroll down faster than it should and then I can't see which channel/game I'm selecting.
My TV model might be too old. I'm losing hope of this working for me.

**Comment by nikitakatchik** [comment]
Hi, installation IP address is no longer being provided, so you'll have to get a local web server up to install the app. Check the tips in README.md for more info.
