### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by leotm** [nikitakatchik/smarttv-twitch#104]
Tried 188.226.130.26.
Tried the other IP.
Tried my local SammyWidgets_v1.1 with widgets/Twitch-BrunoN.zip IP.
Tried changing my UE40HU6900 IP from automatic to manually match the local IP above.
Watched through all the Bruno N videos.
In the UK.

**Comment by ryanlough** [comment]
Same here. It looks like the given IP no longer responds to any requests.

**Comment by freesoulmoon** [comment]
Same here.Help.twich has been delated automatcally from my samsung tv and the ip doesnt work anymore....any news???

**Comment by nikitakatchik** [comment]
Unfortunately the host we used doesn't seem to work anymore.

**Comment by zyandev** [comment]
So what do i have to do? With 3.6 gives me error "Error installing. For more information, visit http://www.samsungdforum.com/Support/TVAppsSecurity

AnalysisResult contents is NULL.

**Comment by suliohad** [comment]
Will you fix the IP installing? I think I can still install via IP on my F6400

**Comment by rjunior** [comment]
ERROR_DEVELOPMENT_002 in my Samsung UN40FH5303GXZD.
How do I fix it?

**Comment by Resi70** [comment]
Search for SammyWidgets_v1.1 and run this on you pc. Its so much easier then installing a webserver. i have a E series here but i think it will work on other series to.

https://www.youtube.com/watch?v=ZiVtKbJWFtE&t=39s

On the tv follow the normal steps when you have a webserver installed and want to install it for you series
All the apps in the widget folder will be synced so you can install and sync more apps at once

**Comment by rjunior** [comment]
@Resi70 ... It has worked really well. Thanks guy!!

**Comment by nikitakatchik** [comment]
Hi, installation IP address is no longer being provided, so you'll have to get a local web server up to install the app. Use suggestions from people above or check the tips in README.md for more info.
