### ISSUE TITLE
Unable to receive access token

### ISSUE THREAD

**Issue by Ottha** [nikitakatchik/smarttv-twitch#111]
For some reason I can’t load streams anymore because the app shows the mentioned error. Could not determine the reason as it does not look like anything in the auth management for the twitch api changed. Maybe more info is available when debugging.

**Comment by founias** [comment]
i have the same problem. I have a 2014 UE40H6400 and i was using the twitch tv app for 2 years. Today i changed my internet connection from adsl to vdsl and also changed routers. Started the twitch app on my tv,chose a channel and after it loads 15/15 i get the Error : Unable to retrieve accerss token. Deleted the app, installed the Twitch Tv BrunoN with the SammyWidget (i was using the old twitch app with just the ip adress while in develop mode) but still nothing.Even changed my dns settings to google ones but nothing changed

**Comment by JaysonStatham** [comment]
Looks like Twitch has removed support for non HTTPS requests to the API

This issue can be fixed by replacing line 536 in SceneChannel.js from:

theUrl = 'http://api.twitch.tv/api/channels/' + SceneSceneBrowser.selectedChannel + '/access_token';

to 

theUrl = 'http**s:**//api.twitch.tv/api/channels/' + SceneSceneBrowser.selectedChannel + '/access_token';

**Comment by sqbi87** [comment]
Hi guys, can anyone fix this new issue with being unable to load any stream so noobs like me can enjoy Twitch app once again on their TV? Is it possible for me to simply update the app via my TV settings?

**Comment by Ottha** [comment]
You‘ll have to wait until the above pull request is merged and a new version created. I guess the creator of the app will let us know in this Channel once it’s done.

**Comment by nikitakatchik** [comment]
Hi, can someone please try this version before I publish it as a release.
[TwitchTV_3.7_America_20180510.zip](https://github.com/nikitakatchik/smarttv-twitch/files/1989176/TwitchTV_3.7_America_20180510.zip)

**Comment by nikitakatchik** [comment]
I meant exactly the package I posted 😃

**Comment by Bvlent** [comment]
Hi,

I've tested your package and it seems to be working. Downloaded the zip, extracted to a USB drive. Plugged it in and it appeared in the Hub. Started from there and streams van be viewed again.

Model: UE48H5500

Thanks!

**Comment by Ottha** [comment]
@nikitakatchik could you put a link to the readme pointing to the Samsung docs about how to get apps to the tv? I guess there are multiple ways but I couldn’t find the most convenient one for me yet. Used the old way with your server for sharing but didn’t check out at that point how it works.

**Comment by nikitakatchik** [comment]
Good work everyone, it's now published as release 3.7.

@Ottha Okay, I'll post some official links.
