### ISSUE TITLE
Error: Unable to retrieve access token. Since ~3 days.

### ISSUE THREAD

**Issue by GurkenKater** [nikitakatchik/smarttv-twitch#114]
Hey guys, there's this problem since some days. (My english is bad, sorry :)) You can't watch any Channel. 
I just wanted to see which Version of the app I have, but I got the the message that the Samsung Server does not response or something. 
The App loads normaly, you just can't start Streams.
I just watch Twitch Steams with this App for years. It would be cool if someone could fix this. :)
I have a Samsung UE32H6470

**Comment by neryreginato** [comment]
It's solved already.

https://github.com/nikitakatchik/smarttv-twitch/issues/113

Download the new version. 3.7

**Comment by nikitakatchik** [comment]
@GurkenKater @neryreginato That's right.
